CREATE DATABASE IF NOT EXISTS RRInventoryManagement;

USE RRInventoryManagement;

CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    superuser BOOLEAN DEFAULT FALSE NOT NULL
);